# encoding: utf-8
# This file is generated by ModuleSync, do not edit.
# put local configuration and setup into spec_helper_local
begin
  require 'spec_helper_local'
rescue LoadError => e
  raise unless e.message =~ %r{spec_helper_local}
  puts 'Skipping Local config as spec_helper_local not found'
end
